test_name: "6dof"
group_name: "manipulator"
base_link: "world"
last_link: "flange"
moving_obs: true
disp_verb_informed: false
disp_verb_pathSwitch: false
time_verb: false
time_for_repl: 0.1
opt_path: true
start_configuration: [1.5, 0.5, -0.5, -1.5, -0.7, 0.7]
stop_configuration: [0.0, 0.0, -1.0, 0.0, -1.5, 1.0]
n_test: 1
